### PR TITLE
reader: unzip and untar data without checking the filename

### PR DESCRIPTION
**Pull request by s-stepien**
Recently, MaxMind has changed the URL from which the free database can
be downloaded. In the new URL schema, the suffix is given as a URL
parameter, so we need to handle it correctly during unpacking.

Signed-off-by: Sławomir Stępień <sst@poczta.fm>

### CODE REVIEW

**Comment by s-stepien** [comment]
Well, this is not the best thing we can do. It would be better for parse the URL, but would be super nice to check the headers (if this is even possible) and detect gnuzip and tar type data. I will take a look at better approach.

**Comment by s-stepien** [comment]
Commit updated. I think this is better approach.

**Review by mneudert — APPROVED** [review]
:heart: :blue_heart: :green_heart: :purple_heart: :yellow_heart:

**Comment by mneudert** [comment]
Just out of curiosity I ran a benchmark with the changes:

```elixir
Benchee.run(
  %{
    "read" => fn -> Geolix.Adapter.MMDB2.Reader.read_database("GeoLite2-City.mmdb") end
  },
  formatters: [{Benchee.Formatters.Console, comparison: false}],
  warmup: 2,
  time: 10
)
```

Following values where output using an already unpacked City database (50-somewhat MB):

```
# untar/unzip with suffix check
Name           ips        average  deviation         median         99th %
read        135.48        7.38 ms    ±12.45%        7.21 ms        8.61 ms

# always untar/unzip
Name           ips        average  deviation         median         99th %
read         36.83       27.15 ms    ±11.83%       26.63 ms       45.35 ms
```

"Future versions™" might provide a more fine grained control on what to run for reading the file but as far as I am concerned these times they should not matter much right now. And it at allows to use the new download locations :+1:

**Pull request merged**
